bigquery: # BigQuery warehouse profile
  outputs:
    default: # Default target/connection (this will be used by default)
      dataset: iot_telemetry_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: iot-project
      threads: 1
      type: bigquery
    local: # Local (env specific) target/connection
      dataset: "{{ var('profile_gbq_dataset') }}"
      job_execution_timeout_seconds: "{{ var('profile_job_exec_timeout_sec') }}"
      job_retries: "{{ var('profile_job_retry') }}"
      location: "{{ var('profile_gbq_ds_loc') }}"
      method: "{{ var('profile_gbq_auth_method') }}"
      priority: "{{ var('profile_priority') }}"
      project: "{{ var('profile_gcp_project') }}"
      threads: "{{ var('profile_threads') }}"
      type: bigquery
